name: Build calibre package

on:
  push:
    branches: [$default-branch, 'dev']
    tags: ['v*']
  pull_request:
    branches: [$default-branch, 'dev']

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  createCalibrePackage:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: 'moly_hu/pyproject.toml'

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install ./moly_hu[dev]

    - name: Test with pytest
      run: |
        pytest -v moly_hu/tests/

    - name: Create calibre package
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        export RELEASE_VERSION=${{github.ref_name}}
        export RELEASE_FILE_NAME=Calibre_Moly_hu-${RELEASE_VERSION}.zip
        mkdir -p output
        bash ./scripts/create_calibre_plugin_zip.sh ./ ./output/${RELEASE_FILE_NAME}

    - name: Create calibre-web package
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        export RELEASE_VERSION=${{github.ref_name}}
        export RELEASE_FILE_NAME=Calibre-web_Moly_hu-${RELEASE_VERSION}.zip
        mkdir -p output
        bash ./scripts/create_calibreweb_plugin_zip.sh ./ ./output/${RELEASE_FILE_NAME}

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ./output/*
