name: Create new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create package
      run: |
        export RELEASE_VERSION=${{github.ref_name}}
        export RELEASE_FILE_NAME=Moly_hu_Reloaded-${RELEASE_VERSION}.zip
        mkdir output
        bash ./scripts/create_plugin_zip.sh ./ ./output/${RELEASE_FILE_NAME}

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: ./output/*
